# Generated by Django 2.2.12 on 2020-05-26 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('customer', models.CharField(default='empty', max_length=100)),
                ('executor', models.CharField(default='empty', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('date_deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline on')),
                ('status', models.CharField(choices=[('ЗАКРЫТЫЙ', 'Закрытый'), ('ОТКРЫТЫЙ', 'Открытый')], default='ОТКРЫТЫЙ', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.CharField(choices=[('БЕЗ ОЦЕНКИ', 'Без оценки'), ('УЖАСНО', 'Ужасно'), ('ПЛОХО', 'Плохо'), ('УДОВЛЕТВОРИТЕЛЬНО', 'Удовлетворительно'), ('ХОРОШО', 'Хорошо'), ('ОТЛИЧНО', 'Отлично')], default='БЕЗ ОЦЕНКИ', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlatformApp.StudyProject')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
