# Generated by Django 3.0.5 on 2020-05-05 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlatformApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyproject',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
