# Generated by Django 2.2.12 on 2020-05-26 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlatformApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyproject',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_executor', to=settings.AUTH_USER_MODEL),
        ),
    ]
