# Generated by Django 2.2.12 on 2020-05-26 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlatformApp', '0002_auto_20200526_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.CharField(choices=[('БЕЗ ОЦЕНКИ', 'Без оценки'), ('УЖАСНО', 'Ужасно'), ('ПЛОХО', 'Плохо'), ('УДОВЛЕТВОРИТЕЛЬНО', 'Удовлетворительно'), ('ХОРОШО', 'Хорошо'), ('ОТЛИЧНО', 'Отлично')], default='БЕЗ ОЦЕНКИ', max_length=100, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlatformApp.StudyProject', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_author', to=settings.AUTH_USER_MODEL, verbose_name='Создатель проекта'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='date_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок выполение'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='status',
            field=models.CharField(choices=[('ЗАКРЫТЫЙ', 'Закрытый'), ('ОТКРЫТЫЙ', 'Открытый')], default='ОТКРЫТЫЙ', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
