# Generated by Django 2.2.12 on 2020-05-26 02:46

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlatformApp', '0003_auto_20200526_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyproject',
            name='attached_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/proj_files'), upload_to='', verbose_name='Прикрепленные файлы'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='date_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок выполения'),
        ),
        migrations.AlterField(
            model_name='studyproject',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
