# Generated by Django 2.2.12 on 2020-05-26 03:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatformApp', '0004_auto_20200526_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyproject',
            name='attached_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/proj_files'), upload_to='proj_files', verbose_name='Прикрепленные файлы'),
        ),
    ]
