# Generated by Django 2.2.12 on 2020-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlatformApp', '0005_auto_20200526_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyproject',
            name='attached_file',
            field=models.FileField(null=True, upload_to='proj_files', verbose_name='Прикрепленные файлы'),
        ),
    ]
